### ISSUE TITLE
References are in square backets

### ISSUE THREAD

**Issue by paolapasino** [ka1/zot2indd#6]
First, thank you for zot2indd, it is amazing. Just a small thing. References are in [ ] while my university requires them to be in ( ). Can this be changed? is there a setting somewhere?

Thanks

Paola

**Comment by ka1** [comment]
Hi Paola,
glad to hear that zot2indd is useful for you. Just a quick "hack": In the sourcecode, I now added two new variables, intextRefCharStart and intextRefCharEnd. You can change these in the lines 46 and 47. I might create a field in the user interface for that once I have a little more time on my hands... I'll let you know.

So please pull the recent version and change the variables to () on your local copy.
Does that work for you?
Kai

**Comment by paolapasino** [comment]
Kai

I will try tomorrow and will let you know! Thanks for replying so quickly!!!

Regards

Paola

**Comment by paolapasino** [comment]
Kai,
it worked like a charm. Perfect. Thank you again for your email

Regards

Paola

**Comment by ka1** [comment]
Perfect, let me know if there is any more problems.
Regards,
Kai

> Am 11.11.2015 um 08:22 schrieb paolapasino notifications@github.com:
> 
> Kai,
> it worked like a charm. Perfect. Thank you again for your email
> 
> Regards
> 
> Paola
>
