### ISSUE TITLE
Same author, same year, but more than one title

### ISSUE THREAD

**Issue by raphabenoi** [ka1/zot2indd#7]
Hey,
first things first: thank you so much for the great work you did there!
I have a little problem if the same author created more than one document in the same year.
How can I solve this problem?
Thanks in advance for your help,
cheers,
Rapha

**Comment by ka1** [comment]
Hi Rapha,
glad you like the tool! I had to check in my bibliography, but I remembered that I implemented a function
to allow things like milgram1994 and milgram1994-1
If I remember right, the Zotero-exporters ("BibTexCiteKeyOnly.js" and "MODS modified by Kai.js“) supported the export
of such duplicates from zotero. Did you try those?
Hope that helps,
Kai

**Comment by raphabenoi** [comment]
Hey, indeed!
It worked perfectly ;) thank you 👍 
Rapha
