### ISSUE TITLE
InDesign script appears to have a document character limit

### ISSUE THREAD

**Issue by itsonlyluis** [ka1/zot2indd#8]
I realise this script is very old, but I find it very useful when writing documents in ID.

From what I can tell, the InDesign script stops working (doesn't find new references anywhere) if the document has more than 2^16 characters in total, across all stories.

Thanks :)

**Comment by ka1** [comment]
Thank you for your comment, glad that it helps you! I had a look in the document where I used the script. It is about 500.000 characters / way more than 2^16 or even 2^18, so I cannot reproduce your issue. Sorry, it must be something else.
